model: cnn
batch_size: 32
n_epochs: 10
learning_rate: 0.0001

cnn:
  n_layers: 12
  depth: 1
  channels: [20,30,45,67,100,150,225,337,505,757,1135,1702]
  kernels: [3,3,3,3,3,3,3,3,3,3,3,3]
  n_classes: 2
  classifier: gap_fc # fc / gap_fc / gap
